### ISSUE TITLE
limitation-error with option file-usage

### ISSUE THREAD

**Issue by wikiUserPG** [magnusmanske/petscan_rs#110] opened 2021-12-13 13:18 UTC
the query for _all files on commons in [Category:SVG national flags of Germany](https://commons.wikimedia.org/wiki/Category:SVG_national_flags_of_Germany) in addition with `File usage data`_ (tab `output`) results a `PageList::run_batch_query: SQL query error[2]: Io(Io(Custom { kind: Other, error: "packet too large" }))`

this is a similar [query](https://petscan.wmflabs.org/?psid=20875975) which dont results in a limitation-error-message

i guess result must be really big, therefor this is no bug but to expect
so for this request but also for other i sugguest to limit the option `File usage data` for specific wikiprojects in combination with a namespace (e.g. `dewiki:10` for files in templates in de-wiki or `enwiki:0` for files in enwiki in main/articles), the list of those filtercriterias should be coma-separated ("dewiki:10,dewiktionary:103,enwiki:0")
see [dewiki-namespaces](https://de.wikipedia.org/wiki/Hilfe:Namensr%C3%A4ume) and [enwiki-namespaces](https://en.wikipedia.org/wiki/Wikipedia:Namespace) for example

i also suggest the option to sort the results by the number of usage-counts

since this is no bug i ask myself if this is the correct place for for this issue?
thx

**Comment by dpriskorn** [comment] 2021-12-14 13:08
I would say that it is a bug. PetScan should tell the user what failed in clear text and impose sane limits and enforce them

**Comment by magnusmanske** [comment] 2024-01-23 12:45
The query actually runs well, but when adding the file usage data, the MySQL query for just the 25 files throws "package too large" error, presumably because of too many pages in too many wikis using these files.

I can't run that query for each individual file _per se_ because there might be hundreds of thousands of files with little usage.

**Comment by magnusmanske** [comment] 2024-01-23 13:08
Turns out this is caused by even individual files. I can not change `max_allowed_packet` on the Commons replica so I can't fix it in MariaDB.

I do not see a feasible way around this so I'm closing it.

I have added a mitigation that will keep trying by reducing the batch size for the queries, but in this case it will eventually run to batch size 0...

**Closed** 2024-01-23 13:08 UTC
