### ISSUE TITLE
petscan tool is very unstable or even down (502 Bad Gateway error)

### ISSUE THREAD

**Issue by Nirvanchik** [magnusmanske/petscan_rs#38] opened 2020-02-23 12:07 UTC
Last 3 days (21, 22, 23 February) petscan was failing a lot.
Sometimes it gives "502 Bad Gateway", even on light requests like "http://petscan.wmflabs.org/?language=ru&project=wikipedia&depth=1&categories=HTML&ns%5B0%5D=1&sortby=title&format=tsv&doit=" - this is a lite check (health) request that my software (bot) does before doing its real jobs.

I was getting about 100 failed tasks per day (and this is about ~300-500 failed requests in petscan).
This is about 20% of all tasks that my software does.

**Comment by SednaBoo** [comment] 2020-02-25 21:49
I have never had success with the new version.  I used the old one until the plug was pulled, but now I can't seem to do anything i need.

**Comment by magnusmanske** [comment] 2020-02-26 12:56
@Nirvanchik Hard to debug, this. PetScan should automatically restart when it breaks. If your bot has an issue, have it wait for ~20sec and retry. I have fixed a few other issues today, maybe this issue have been resolved as a result. Note also that there was a recent VM reboot at Labs where PetScan did not come up again and I had to restart it manually; that would have caused a few hours of 502.

@SednaBoo "It doesn't work" is not a bug report, just whining. If there are concrete queries that fail for you, please open issues for them here, with example, and expected outcome.

**Comment by Nirvanchik** [comment] 2020-02-27 10:03
> If your bot has an issue, have it wait for ~20sec and retry

Thanks for advise! And thanks for fixes.

**Comment by magnusmanske** [comment] 2020-02-28 11:59
I have made some improvements to the RAM footprint, up 75% less memory now. That should help with stability. I am also recording queries that were running when PetScan dies, in case there are some "killer conditions". I'll close this bug in a few days unless I hear the instability is continuing.

**Comment by magnusmanske** [comment] 2020-03-06 11:22
Closing this for now, as it's too vague to address, and PetScan seems a lot more stable now. Please open a new issue if you find queries that consistently break PetScan.

**Closed by magnusmanske** 2020-03-06 11:22 UTC
